language: python

python:
  - "3.5"
  - "3.6"


install:
  - pip install -r requirements-dev.txt
  - pip install mypy
  - pip install codecov

script:
  - make flake
  - pytest tests --cov=janus
  - mypy janus


cache:
  - apt
  - directories:
    - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
    codecov

deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: HhuGwcUoaxo/9zwCzNKA4/eIeuHJa/rt92LDQO+V5k3W1w1ALNtzcz7j18YvIFnxfPoh0kON3t78jfddTBEnaoKy5oUH+O3A07V23aMAoYXjs6UIht4oqYQSqncRH+yreL74OexliuVrsnOuKmxYPyhiJdJ1OVBaCa0e43iblGFSkVLP9wQSrleWb3kgKjS/kaAJ0+UEGuDH7GPkozL3NR3IqtJYbulJ0MjORSblXyRCR5FV8ag0yVRjj5p2+8uXl4T53VNPecJ415q1wFt22RzJBI/orYmE90baZSwRUg3d6cj7QX689y9qvQ9Gc9QPiRJiQB1V9BmuLx7WQbvM/Nu470aMPFAKuLtJKdDcAc1z/+l4/d5kidMVZ+vFZftub66I6mREZeHjvJdnOaEPcHYk/Vm8a2aau3H4dt/4rYLQpqwt/LFUD2IiTimUdiJU/MNx1S4fMxobHUXRecQIQtXYdhY3j+eZKhBuiBodHIXbgnsT1myrBIEbNceMVVgfjFQOFid7dXkqWGvuT3onB51DeKixhdjR26pPX+8INYKiSS+ZgFy0K5YV5f3ShGO+QlT2kJv4IrixO7H/JfPCLI9L7P5T2D7viuPqDz6Ik5TiAMkWgKXwspEQSNi68k46WHoaQHl73EJy+XuCLBgs9oFL6iZ+ADvFvvoGu7hAmtQ=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.6
